"""THE PORTFOLIO CORRELATION MEASUREMENT.

Measures the pairwise correlation matrix of all five sleeves plus the passive benchmark,
then the portfolio Sharpe of every combination using the MEASURED covariance matrix.

No new data, no new strategy, no new signal. Every input is a return series a prior study
already persisted (or, for low-vol, one regenerated by re-running the registered code path
under a 1e-9 reproduction gate -- see `extract_lowvol_monthly.py`).

Writes only into `research/sleeves/_portfolio/` and
`research/sleeves/portfolio_correlation_result.md` (concurrency scope).

    .venv/Scripts/python.exe -m research.sleeves._portfolio.portfolio_correlation
"""

from __future__ import annotations

import itertools
import json
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parents[3]
SLEEVES = REPO / "research" / "sleeves"
OUT_DIR = SLEEVES / "_portfolio"
MPY = 12
RNG = np.random.default_rng(20260728)

# --------------------------------------------------------------------------------------
# 1. THE REGISTERED SERIES. Each entry: (label, path, column, what it is).
# --------------------------------------------------------------------------------------
SOURCES = {
    "lowvol": (OUT_DIR / "lowvol_b2_net_monthly.parquet", "net_conservative",
               "low-vol/quality band B2, US equities (Sharadar), DEV window, "
               "conservative cost bound"),
    "trend": (SLEEVES / "_multiasset_trend" / "primary_20pct_monthly.csv", "net_10bps",
              "multi-asset time-series momentum, 18 instruments, 20% vol target, 10bps"),
    "carry": (SLEEVES / "_carry_output" / "carry_primary_net_monthly.parquet", "net",
              "cross-asset carry, 13 instruments, 10bps conservative"),
    "seasonal": (SLEEVES / "_seasonal" / "seasonal_composite_20pct_monthly.parquet",
                 "seasonal_net_10bps",
                 "seasonal composite (turn-of-month + Halloween + January), 20% vol, 10bps"),
    "defensive": (SLEEVES / "_defensive" / "primary_20pct_monthly.csv", "net_10bps",
                  "defensive / betting-against-beta, 20% vol target, 10bps"),
    "passive": (SLEEVES / "_seasonal" / "seasonal_composite_20pct_monthly.parquet",
                "bench_net_10bps",
                "equal-weight buy-and-hold of the 18 panel instruments (registered "
                "benchmark, Sharpe 0.7065)"),
}
SLEEVE_NAMES = ["lowvol", "trend", "carry", "seasonal", "defensive"]
ALL_NAMES = SLEEVE_NAMES + ["passive"]


def _load(path: Path, col: str) -> pd.Series:
    if path.suffix == ".csv":
        df = pd.read_csv(path, parse_dates=["date"]).set_index("date")
    else:
        df = pd.read_parquet(path)
    s = df[col].astype(float).dropna()
    s.index = pd.DatetimeIndex(s.index).to_period("M").to_timestamp(how="end").normalize()
    return s


def sharpe(x: pd.Series | np.ndarray) -> float:
    a = np.asarray(pd.Series(x).dropna(), dtype=float)
    if len(a) < 3 or np.std(a, ddof=1) == 0:
        return float("nan")
    return float(np.mean(a) / np.std(a, ddof=1) * np.sqrt(MPY))


def ann_vol(x) -> float:
    a = np.asarray(pd.Series(x).dropna(), dtype=float)
    return float(np.std(a, ddof=1) * np.sqrt(MPY))


def max_dd(x) -> float:
    a = np.asarray(pd.Series(x).dropna(), dtype=float)
    eq = np.cumprod(1.0 + a)
    return float(np.min(eq / np.maximum.accumulate(eq)) - 1.0)


def fisher_ci(r: float, n: int, alpha: float = 0.05) -> tuple[float, float, float]:
    """Fisher-z CI for a correlation. Returns (se_of_r, lo, hi)."""
    if n < 5 or abs(r) >= 1:
        return (float("nan"),) * 3
    z = np.arctanh(r)
    se_z = 1.0 / np.sqrt(n - 3)
    crit = 1.959963984540054
    lo, hi = np.tanh(z - crit * se_z), np.tanh(z + crit * se_z)
    se_r = (1 - r ** 2) / np.sqrt(n - 3)          # delta-method SE on the r scale
    return float(se_r), float(lo), float(hi)


def block_bootstrap_corr(a: np.ndarray, b: np.ndarray, block: int = 12,
                         n_boot: int = 4000) -> tuple[float, float]:
    """Stationary-block bootstrap CI for a correlation (handles autocorrelation)."""
    n = len(a)
    if n < block * 3:
        block = max(2, n // 6)
    n_blocks = int(np.ceil(n / block))
    out = np.empty(n_boot)
    for i in range(n_boot):
        starts = RNG.integers(0, n - block + 1, size=n_blocks)
        idx = np.concatenate([np.arange(s, s + block) for s in starts])[:n]
        aa, bb = a[idx], b[idx]
        sa, sb = aa.std(ddof=1), bb.std(ddof=1)
        out[i] = np.nan if sa == 0 or sb == 0 else np.corrcoef(aa, bb)[0, 1]
    out = out[~np.isnan(out)]
    return float(np.percentile(out, 2.5)), float(np.percentile(out, 97.5))


def block_bootstrap_sharpe(r: np.ndarray, block: int = 12,
                           n_boot: int = 4000) -> tuple[float, float]:
    n = len(r)
    if n < block * 3:
        block = max(2, n // 6)
    n_blocks = int(np.ceil(n / block))
    out = np.empty(n_boot)
    for i in range(n_boot):
        starts = RNG.integers(0, n - block + 1, size=n_blocks)
        idx = np.concatenate([np.arange(s, s + block) for s in starts])[:n]
        x = r[idx]
        out[i] = np.mean(x) / np.std(x, ddof=1) * np.sqrt(MPY) if x.std(ddof=1) > 0 else np.nan
    out = out[~np.isnan(out)]
    return float(np.percentile(out, 2.5)), float(np.percentile(out, 97.5))


# --------------------------------------------------------------------------------------
# 2. PORTFOLIO CONSTRUCTION on the MEASURED covariance matrix.
# --------------------------------------------------------------------------------------
def inverse_vol_weights(X: pd.DataFrame) -> np.ndarray:
    w = 1.0 / X.std(ddof=1).to_numpy()
    return w / w.sum()


def inverse_variance_weights(X: pd.DataFrame) -> np.ndarray:
    w = 1.0 / X.var(ddof=1).to_numpy()
    return w / w.sum()


def erc_weights(X: pd.DataFrame, iters: int = 20000, tol: float = 1e-12) -> np.ndarray:
    """True equal-risk-contribution weights from the MEASURED covariance matrix."""
    cov = X.cov(ddof=1).to_numpy()
    n = cov.shape[0]
    w = np.ones(n) / n
    for _ in range(iters):
        mrc = cov @ w
        rc = w * mrc
        target = rc.mean()
        new = w * (target / np.maximum(rc, 1e-18)) ** 0.5
        new = np.maximum(new, 1e-12)
        new /= new.sum()
        if np.max(np.abs(new - w)) < tol:
            w = new
            break
        w = new
    return w


def portfolio_stats(X: pd.DataFrame, w: np.ndarray) -> dict:
    port = X.to_numpy() @ w
    return {
        "sharpe": sharpe(port),
        "vol": ann_vol(port),
        "mean_annual": float(np.mean(port) * MPY),
        "max_dd": max_dd(port),
        "weights": {c: float(x) for c, x in zip(X.columns, w)},
    }


def equal_sharpe_shortcut(X: pd.DataFrame) -> float:
    """The formula the programme banned. Reported only to re-demonstrate its error."""
    s = float(np.mean([sharpe(X[c]) for c in X.columns]))
    n = X.shape[1]
    rho = X.corr().to_numpy()
    off = rho[np.triu_indices(n, 1)]
    rbar = float(np.mean(off)) if len(off) else 0.0
    denom = 1 + (n - 1) * rbar
    return float(s * np.sqrt(n / denom)) if denom > 0 else float("nan")


def main() -> int:
    series = {k: _load(p, c) for k, (p, c, _) in SOURCES.items()}
    report: dict = {"series": {}, "pairwise": [], "combinations": [],
                    "common_window": {}, "diagnostics": {}}

    for k, s in series.items():
        report["series"][k] = {
            "source": str(SOURCES[k][0].relative_to(REPO)).replace("\\", "/"),
            "column": SOURCES[k][1],
            "description": SOURCES[k][2],
            "n_months": int(len(s)),
            "first": str(s.index.min().date()),
            "last": str(s.index.max().date()),
            "sharpe": sharpe(s),
            "ann_vol": ann_vol(s),
            "mean_annual": float(s.mean() * MPY),
            "max_dd": max_dd(s),
        }

    # ---- pairwise correlations on OVERLAPPING months only ---------------------------
    for a, b in itertools.combinations(ALL_NAMES, 2):
        sa, sb = series[a], series[b]
        idx = sa.index.intersection(sb.index)
        x, y = sa.reindex(idx).to_numpy(), sb.reindex(idx).to_numpy()
        r = float(np.corrcoef(x, y)[0, 1])
        se, lo, hi = fisher_ci(r, len(idx))
        blo, bhi = block_bootstrap_corr(x, y)
        report["pairwise"].append({
            "a": a, "b": b, "n_overlap": int(len(idx)),
            "first": str(idx.min().date()), "last": str(idx.max().date()),
            "rho": r, "se": se, "ci95_fisher": [lo, hi], "ci95_block_boot": [blo, bhi],
        })

    # ---- every combination, each on its own maximal overlap --------------------------
    for size in range(1, len(SLEEVE_NAMES) + 1):
        for combo in itertools.combinations(SLEEVE_NAMES, size):
            frame = pd.concat({c: series[c] for c in combo}, axis=1).dropna()
            if len(frame) < 24:
                continue
            entry = {
                "combo": list(combo), "n_months": int(len(frame)),
                "first": str(frame.index.min().date()),
                "last": str(frame.index.max().date()),
                "inverse_vol": portfolio_stats(frame, inverse_vol_weights(frame)),
                "inverse_variance": portfolio_stats(frame, inverse_variance_weights(frame)),
                "erc": portfolio_stats(frame, erc_weights(frame)),
            }
            if size > 1:
                entry["equal_sharpe_shortcut"] = equal_sharpe_shortcut(frame)
            report["combinations"].append(entry)

    # ---- apples-to-apples: every combination on ONE common window --------------------
    common = None
    for c in SLEEVE_NAMES:
        common = series[c].index if common is None else common.intersection(series[c].index)
    cw = pd.concat({c: series[c] for c in SLEEVE_NAMES + ["passive"]}, axis=1).dropna()
    report["common_window"]["n_months"] = int(len(cw))
    report["common_window"]["first"] = str(cw.index.min().date())
    report["common_window"]["last"] = str(cw.index.max().date())
    report["common_window"]["sleeve_sharpes"] = {c: sharpe(cw[c]) for c in cw.columns}
    report["common_window"]["corr"] = cw.corr().round(6).to_dict()
    cw_combos = []
    for size in range(1, len(ALL_NAMES) + 1):
        for combo in itertools.combinations(ALL_NAMES, size):
            frame = cw[list(combo)]
            cw_combos.append({
                "combo": list(combo),
                "inverse_vol": portfolio_stats(frame, inverse_vol_weights(frame)),
                "inverse_variance": portfolio_stats(frame, inverse_variance_weights(frame)),
                "erc": portfolio_stats(frame, erc_weights(frame)),
            })
    report["common_window"]["combinations"] = cw_combos

    # ---- OVERLAP DIAGNOSTICS ---------------------------------------------------------
    diag = report["diagnostics"]

    # (a) Is a pair's correlation an artefact of WHICH months overlap? Re-measure every
    #     multi-asset pair on the low-vol window and compare to its full-overlap value.
    lv_idx = series["lowvol"].index
    win = []
    for a, b in itertools.combinations(ALL_NAMES, 2):
        if a == "lowvol" or b == "lowvol":
            continue
        full = series[a].index.intersection(series[b].index)
        sub = full.intersection(lv_idx)
        if len(sub) < 24:
            continue
        r_full = float(np.corrcoef(series[a].reindex(full), series[b].reindex(full))[0, 1])
        r_sub = float(np.corrcoef(series[a].reindex(sub), series[b].reindex(sub))[0, 1])
        win.append({"a": a, "b": b, "n_full": int(len(full)), "rho_full": r_full,
                    "n_lowvol_window": int(len(sub)), "rho_lowvol_window": r_sub,
                    "delta": r_sub - r_full})
    diag["window_sensitivity"] = win

    # (b) Lead-lag profile. If the contemporaneous correlation is not distinguished from
    #     its neighbours, it is noise rather than a measured relationship.
    ll = {}
    for other in ["trend", "carry", "seasonal", "defensive", "passive"]:
        idx = series["lowvol"].index.intersection(series[other].index)
        if len(idx) < 36:
            continue
        a = series["lowvol"].reindex(idx).to_numpy()
        b_full = series[other]
        row = {}
        for shift_k in range(-6, 7):
            shifted = b_full.shift(shift_k).reindex(idx)
            m = ~shifted.isna()
            if m.sum() < 30:
                continue
            row[str(k)] = float(np.corrcoef(a[m.to_numpy()], shifted[m])[0, 1])
        ll[other] = row
    diag["lowvol_lead_lag"] = ll

    # (c) Partial correlation controlling for the passive benchmark -- the mechanical
    #     common factor. Survives => the independence is economic, not just "different desk".
    part = []
    for a, b in itertools.combinations(SLEEVE_NAMES, 2):
        idx = series[a].index.intersection(series[b].index).intersection(series["passive"].index)
        if len(idx) < 30:
            continue
        A = series[a].reindex(idx).to_numpy()
        B = series[b].reindex(idx).to_numpy()
        P = series["passive"].reindex(idx).to_numpy()
        ra = A - np.polyval(np.polyfit(P, A, 1), P)
        rb = B - np.polyval(np.polyfit(P, B, 1), P)
        part.append({"a": a, "b": b, "n": int(len(idx)),
                     "rho_raw": float(np.corrcoef(A, B)[0, 1]),
                     "rho_partial_ex_passive": float(np.corrcoef(ra, rb)[0, 1])})
    diag["partial_correlation_ex_passive"] = part

    # (d) Split-half stability of every pair.
    half = []
    for a, b in itertools.combinations(ALL_NAMES, 2):
        idx = series[a].index.intersection(series[b].index)
        if len(idx) < 60:
            continue
        mid = len(idx) // 2
        A, B = series[a].reindex(idx).to_numpy(), series[b].reindex(idx).to_numpy()
        half.append({"a": a, "b": b, "n": int(len(idx)),
                     "rho_first_half": float(np.corrcoef(A[:mid], B[:mid])[0, 1]),
                     "rho_second_half": float(np.corrcoef(A[mid:], B[mid:])[0, 1])})
    diag["split_half"] = half

    (OUT_DIR / "portfolio_correlation_result.json").write_text(
        json.dumps(report, indent=2, default=str), encoding="utf-8")
    print(json.dumps({"n_pairs": len(report["pairwise"]),
                      "n_combos": len(report["combinations"]),
                      "common_window_n": report["common_window"]["n_months"]}, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
