"""initial persistence schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-17

Binds to ``ops.sql_models.Base.metadata`` so the migration can never drift from
the ORM schema (the same metadata ``SqlStateStore`` creates via ``create_all``).
Future schema changes get their own per-table autogenerated migrations.
"""

from __future__ import annotations

from alembic import op

from ops.sql_models import Base

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    Base.metadata.create_all(op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(op.get_bind())
