"""
TradingEngineResearch — Real price-derived feature ingestion
=================================================
Fetches real daily prices (yfinance) and computes the point-in-time-safe,
price-derivable subset of the model feature set, registering them into the
``feature_store`` so ``get_features`` returns real values. Non-price features
(insider flow, sentiment, OFI, earnings proximity, …) are left to the feature
store's deterministic imputation — they require sources yfinance does not provide.

Tests run on a committed offline fixture (``tests/fixtures/prices_sample.csv``)
that is fully SYNTHETIC — generated by ``scripts/make_synthetic_fixtures.py``,
never recorded from yfinance (Yahoo's ToS forbid redistributing its data). The
live ``fetch_prices`` is network-only and not exercised by the test suite.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd

from data import feature_store
from data.data_contracts import FeatureRow

logger = logging.getLogger(__name__)

__all__ = [
    "PRICE_FEATURES", "fetch_prices", "load_prices", "compute_price_features", "ingest_prices",
    "fetch_dividends", "load_dividends", "trailing_dividend_yields",
    "fetch_news", "news_items_from_yfinance",
]

# Price-derivable subset of FEATURE_NAMES — every window below is trailing (PIT-safe).
PRICE_FEATURES = [
    "momentum_12_1",
    "reversal_5d",
    "volume_ratio",
    "adv_ratio",
    "overnight_gap_mean",
    "idiosyncratic_vol",
]

_TRADING_DAYS = 252
_PRICE_COLUMNS = ["date", "symbol", "open", "high", "low", "close", "volume"]


def fetch_prices(symbols: list[str], start: str, end: str) -> pd.DataFrame:  # pragma: no cover
    """Fetch daily OHLCV from yfinance → tidy long DataFrame (network; not unit-tested)."""
    import yfinance as yf

    raw = yf.download(symbols, start=start, end=end, interval="1d",
                      progress=False, auto_adjust=True)
    frames: list[pd.DataFrame] = []
    for sym in symbols:
        sub = pd.DataFrame({
            "open": raw["Open"][sym], "high": raw["High"][sym], "low": raw["Low"][sym],
            "close": raw["Close"][sym], "volume": raw["Volume"][sym],
        }).dropna()
        sub["symbol"] = sym
        sub.index.name = "date"
        frames.append(sub.reset_index())
    return pd.concat(frames, ignore_index=True)[_PRICE_COLUMNS]


def to_wide(tidy: pd.DataFrame) -> pd.DataFrame:
    """Tidy long OHLCV (``date,symbol,…,close``) → the WIDE close-price matrix
    (``DatetimeIndex`` × symbol) that the engine's ``build_cycle_inputs`` and the
    backtester consume. Keeps only dates where EVERY requested symbol has a close
    (``dropna(how="any")``) so a partial bar never produces a half-empty cross-section.

    This is the shaping the LIVE price provider and the backtest scripts both need; calling
    ``fetch_prices`` without it yields a tidy frame that ``build_cycle_inputs`` rejects."""
    wide = tidy.pivot(index="date", columns="symbol", values="close").sort_index()
    idx = pd.to_datetime(wide.index)
    # tz-AWARE UTC index — the canonical LIVE convention (the feature store fail-closes on a naive
    # asof, and a naive price index would mix with the aware asof/fills and crash the tracker).
    wide.index = idx.tz_localize("UTC") if idx.tz is None else idx.tz_convert("UTC")
    wide.columns = [str(c) for c in wide.columns]
    return wide.dropna(how="any")


def load_prices(path: str | Path) -> pd.DataFrame:
    """Load a recorded price fixture (tidy CSV) → DataFrame with a datetime ``date``."""
    df = pd.read_csv(path)
    df["date"] = pd.to_datetime(df["date"])
    return df


def compute_price_features(
    prices: pd.DataFrame,
) -> dict[tuple[str, pd.Timestamp], dict[str, float]]:
    """Compute the price-derivable feature subset per ``(symbol, date)``.

    Every window is trailing, so a feature at date ``t`` depends only on data
    ``<= t`` (point-in-time safe). Warm-up NaNs and ±inf are dropped. Returns a
    mapping ``(symbol, date) -> {feature: value}``.
    """
    out: dict[tuple[str, pd.Timestamp], dict[str, float]] = {}
    for symbol, group in prices.sort_values("date").groupby("symbol"):
        g = group.set_index("date")
        close = g["close"].astype(float)
        vol = g["volume"].astype(float)
        open_ = g["open"].astype(float)
        ret = close.pct_change()
        adv20 = vol.rolling(20).mean()

        feat_frame = pd.DataFrame({
            "momentum_12_1": close.pct_change(_TRADING_DAYS) - close.pct_change(21),
            "reversal_5d": -close.pct_change(5),
            "volume_ratio": vol / adv20,
            "adv_ratio": adv20 / vol.rolling(60).mean(),
            "overnight_gap_mean": (open_ / close.shift(1) - 1.0).rolling(20).mean(),
            "idiosyncratic_vol": ret.rolling(20).std() * np.sqrt(_TRADING_DAYS),
        }).replace([np.inf, -np.inf], np.nan)

        for date, row in feat_frame.iterrows():
            fdict = {str(k): float(v) for k, v in row.items() if pd.notna(v)}
            if fdict:
                out[(str(symbol), pd.Timestamp(date))] = fdict
    return out


def ingest_prices(prices: pd.DataFrame, mode: str = "RESEARCH") -> int:
    """Compute price features and register PIT-safe ``FeatureRow``s in the store.

    ``asof_timestamp`` is the bar date (tz-aware UTC); ``missing_count`` counts the
    price features not available at that date. Returns the number of rows registered.
    """
    count = 0
    for (symbol, date), fdict in compute_price_features(prices).items():
        asof = pd.Timestamp(date).to_pydatetime()
        if asof.tzinfo is None:
            asof = asof.replace(tzinfo=timezone.utc)
        feature_store._register_features(FeatureRow(
            symbol=symbol,
            asof_timestamp=asof,
            feature_schema_version=feature_store.FEATURE_SCHEMA_VERSION,
            features=fdict,
            freshness_flags={k: False for k in fdict},
            missing_count=len(PRICE_FEATURES) - len(fdict),
        ))
        count += 1
    return count


# ── Dividends (carry sleeve input) ───────────────────────────────────────────────

def fetch_dividends(symbols: list[str], start: str, end: str) -> pd.DataFrame:  # pragma: no cover
    """Fetch the dividend calendar from yfinance → tidy ``date,symbol,dividend`` frame
    (network; not unit-tested). Symbols that paid no dividends contribute no rows."""
    import yfinance as yf

    rows: list[dict] = []
    for sym in symbols:
        series = yf.Ticker(sym).dividends
        if series is None or len(series) == 0:
            continue
        idx = series.index.tz_localize(None) if series.index.tz is not None else series.index
        mask = (idx >= pd.Timestamp(start)) & (idx < pd.Timestamp(end))
        for date, amount in series[mask].items():
            rows.append({"date": pd.Timestamp(date).tz_localize(None), "symbol": sym,
                         "dividend": float(amount)})
    return pd.DataFrame(rows, columns=["date", "symbol", "dividend"])


def load_dividends(path: str | Path) -> pd.DataFrame:
    """Load a recorded dividend fixture (tidy CSV) → DataFrame with a datetime ``date``."""
    df = pd.read_csv(path)
    df["date"] = pd.to_datetime(df["date"])
    return df


def trailing_dividend_yields(
    prices: pd.DataFrame,
    dividends: pd.DataFrame,
    asof: object = None,
    window_days: int = 365,
) -> dict[str, float]:
    """Trailing dividend yield per symbol = (dividends paid in the trailing
    ``window_days``) / (close at ``asof``). Point-in-time safe: only dividends and the
    price ``<= asof`` are used. The universe is taken from ``prices`` columns/symbols, so
    non-payers get 0.0. ``asof`` defaults to the latest price date.
    """
    px = prices.copy()
    px["date"] = pd.to_datetime(px["date"])
    div = dividends.copy()
    if not div.empty:
        div["date"] = pd.to_datetime(div["date"])

    out: dict[str, float] = {}
    for symbol in sorted(px["symbol"].unique()):
        spx = px[px["symbol"] == symbol].sort_values("date")
        as_of = pd.Timestamp(asof) if asof is not None else spx["date"].max()
        eligible = spx[spx["date"] <= as_of]
        if eligible.empty:
            out[str(symbol)] = 0.0
            continue
        close = float(eligible["close"].iloc[-1])
        if close <= 0.0:
            out[str(symbol)] = 0.0
            continue
        window_start = as_of - pd.Timedelta(days=window_days)
        sdiv = div[(div["symbol"] == symbol) & (div["date"] > window_start) & (div["date"] <= as_of)] \
            if not div.empty else div
        ttm = float(sdiv["dividend"].sum()) if not div.empty else 0.0
        out[str(symbol)] = ttm / close
    return out


# ── News (sentiment sleeve / sentiment_score feature input) ──────────────────────

def news_items_from_yfinance(
    raw_items: list,
    symbol: str,
    now: datetime,
) -> list[dict]:
    """Convert yfinance ``Ticker.news`` items into the sentiment pipeline's shape:
    ``{"headline", "age_minutes", "symbol"}``.

    Handles both the modern shape (``{"content": {"title", "pubDate"}}``) and the
    legacy shape (``{"title", "providerPublishTime"}``). Items without a headline or
    a parseable publish time are skipped (no fabricated freshness). ``now`` is
    supplied by the caller — the cycle's asof time, never wall-clock here — and
    future-dated items are skipped (PIT safety).
    """
    if now.tzinfo is None:
        now = now.replace(tzinfo=timezone.utc)

    out: list[dict] = []
    for item in raw_items or []:
        if not isinstance(item, dict):
            continue
        nested = item.get("content")
        content: dict = nested if isinstance(nested, dict) else item
        headline = str(content.get("title") or "").strip()
        if not headline:
            continue

        published: datetime | None = None
        pub_date = content.get("pubDate") or content.get("displayTime")
        epoch = item.get("providerPublishTime") or content.get("providerPublishTime")
        if pub_date is not None:
            try:
                published = pd.Timestamp(str(pub_date)).to_pydatetime()
            except (ValueError, TypeError):
                published = None
        elif epoch is not None:
            try:
                published = datetime.fromtimestamp(float(epoch), tz=timezone.utc)
            except (ValueError, TypeError, OSError):
                published = None
        if published is None:
            continue
        if published.tzinfo is None:
            published = published.replace(tzinfo=timezone.utc)

        age_minutes = (now - published).total_seconds() / 60.0
        if age_minutes < 0.0:
            continue                          # future-dated ⇒ not knowable at `now`
        out.append({"headline": headline, "age_minutes": float(age_minutes),
                    "symbol": str(symbol)})
    return out


def fetch_news(symbols: list[str], now: datetime | None = None) -> list[dict]:  # pragma: no cover
    """Fetch recent headlines per symbol from yfinance → sentiment-pipeline news
    items (network; not unit-tested). yfinance serves only *recent* news, so this
    feeds live/paper cycles — historical backtests cannot be backfilled from it."""
    import yfinance as yf

    now = now or datetime.now(tz=timezone.utc)
    items: list[dict] = []
    for sym in symbols:
        try:
            raw = yf.Ticker(sym).news or []
        except Exception as exc:  # noqa: BLE001 — one symbol's feed must not kill the rest
            logger.warning("fetch_news: %s feed unavailable (%s); skipping.", sym, exc)
            continue
        items.extend(news_items_from_yfinance(raw, sym, now=now))
    return items
